
project_id = "wahxxjnvgexfgebjzwqj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "https://welluraapp.com"
additional_redirect_urls = [
  "https://welluraapp.com/confirm-email", 
  "https://welluraapp.com/reset-password",
  "https://welluraapp.com/auth",
  "http://localhost:5173/reset-password",
  "http://localhost:5173/confirm-email",
  "http://localhost:5173/auth",
  "https://welluraapp.com/login",
  "http://localhost:5173/login",
  "https://welluraapp.com/auth/verify*",
  "https://welluraapp.com/reset-password*",
  "https://welluraapp.com/reset-password?*",
  "https://welluraapp.com/reset-password#*",
  "https://welluraapp.com/reset-password?token=*",
  "https://welluraapp.com/reset-password?type=recovery&token=*",
  "http://localhost:5173/reset-password?token=*",
  "http://localhost:5173/reset-password?type=recovery&token=*",
  "https://welluraapp.com/reset-password?error=*",
  "https://welluraapp.com/reset-password?error_code=*",
  "https://welluraapp.com/reset-password?error_description=*",
  "http://127.0.0.1:5173/reset-password*",
  "http://127.0.0.1:5173/reset-password?token=*",
  "http://127.0.0.1:5173/reset-password?type=recovery&token=*",
  "https://welluraapp.com/reset-password?error=access_denied&error_code=401&error_description=Email+link+is+invalid+or+has+expired",
  "http://localhost:5173/reset-password?error=access_denied&error_code=401&error_description=Email+link+is+invalid+or+has+expired",
  "https://welluraapp.com/reset-password#access_token=*",
  "http://localhost:5173/reset-password#access_token=*",
  "http://127.0.0.1:5173/reset-password#access_token=*"
]

[storage]
enabled = true

[realtime]
enabled = true

[functions.health-lookup]
verify_jwt = true

[functions.google-places-search]
verify_jwt = true
