
project_id = "wahxxjnvgexfgebjzwqj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"

[storage]
enabled = true

[realtime]
enabled = true

[functions.health-lookup]
verify_jwt = true

[functions.google-places-search]
verify_jwt = true
