
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wahxxjnvgexfgebjzwqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhaHh4am52Z2V4ZmdlYmp6d3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNjkzNjEsImV4cCI6MjA1Mzk0NTM2MX0.F1hn8WBIOrdk1Y2ZxH3RiYD_iRshlLQyJq2ivFbO2xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
